### ISSUE TITLE
List_of_countries_by_spoken_languages crashes the app

### ISSUE THREAD

**Issue by atye** [atye/wikitable-api#1]
2020-06-19T19:25:31.677886+00:00 app[web.1]: panic: runtime error: invalid memory address or nil pointer dereference
2020-06-19T19:25:31.677961+00:00 app[web.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x93b4f0]
2020-06-19T19:25:31.677962+00:00 app[web.1]: 
2020-06-19T19:25:31.677962+00:00 app[web.1]: goroutine 53 [running]:
2020-06-19T19:25:31.677969+00:00 app[web.1]: github.com/atye/wikitable-api/service.parseTable.func1.1(0x0, 0xc000ff70b0, 0xc0003efc80)
2020-06-19T19:25:31.677970+00:00 app[web.1]: /wikitable-api/service/service.go:102 +0x230
2020-06-19T19:25:31.677970+00:00 app[web.1]: github.com/PuerkitoBio/goquery.(*Selection).EachWithBreak(0xc000ff7080, 0xc0004618d0, 0x6)
2020-06-19T19:25:31.677970+00:00 app[web.1]: /go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:21 +0x101
2020-06-19T19:25:31.677973+00:00 app[web.1]: github.com/atye/wikitable-api/service.parseTable.func1(0xb, 0xc000ff7050, 0xc000461901)
2020-06-19T19:25:31.677992+00:00 app[web.1]: /wikitable-api/service/service.go:79 +0xa5
2020-06-19T19:25:31.678005+00:00 app[web.1]: github.com/PuerkitoBio/goquery.(*Selection).EachWithBreak(0xc000ff62a0, 0xc000461998, 0x0)
2020-06-19T19:25:31.678023+00:00 app[web.1]: /go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:21 +0x101
2020-06-19T19:25:31.678058+00:00 app[web.1]: github.com/atye/wikitable-api/service.parseTable(0xc000ff6270, 0x0, 0x0, 0x0)
2020-06-19T19:25:31.678066+00:00 app[web.1]: /wikitable-api/service/service.go:77 +0xff
2020-06-19T19:25:31.678082+00:00 app[web.1]: github.com/atye/wikitable-api/service.(*Service).GetTables.func1(0x1c, 0xc000ff6270, 0xc0001c4101)
2020-06-19T19:25:31.678095+00:00 app[web.1]: /wikitable-api/service/service.go:34 +0x4a
2020-06-19T19:25:31.678117+00:00 app[web.1]: github.com/PuerkitoBio/goquery.(*Selection).EachWithBreak(0xc000eeaae0, 0xc000461b10, 0xf)
2020-06-19T19:25:31.678127+00:00 app[web.1]: /go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:21 +0x101
2020-06-19T19:25:31.678165+00:00 app[web.1]: github.com/atye/wikitable-api/service.(*Service).GetTables(0xfd4198, 0xb653e0, 0xc00037d0e0, 0xc00005f380, 0xfd4198, 0xc00037d0e0, 0xc000416ba0)
2020-06-19T19:25:31.678171+00:00 app[web.1]: /wikitable-api/service/service.go:33 +0x3dc
2020-06-19T19:25:31.678260+00:00 app[web.1]: github.com/atye/wikitable-api/service/pb._WikiTable_GetTables_Handler(0x9bc860, 0xfd4198, 0xb653e0, 0xc00037d0e0, 0xc00005f320, 0x0, 0xb653e0, 0xc00037d0e0, 0xc00037e1b0, 0x27)
2020-06-19T19:25:31.678296+00:00 app[web.1]: /wikitable-api/service/pb/wikitable.pb.go:460 +0x217
2020-06-19T19:25:31.678310+00:00 app[web.1]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000273380, 0xb6b980, 0xc000408180, 0xc000382a00, 0xc00007dfb0, 0xf92ec0, 0x0, 0x0, 0x0)
2020-06-19T19:25:31.678311+00:00 app[web.1]: /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x50a
2020-06-19T19:25:31.678314+00:00 app[web.1]: google.golang.org/grpc.(*Server).handleStream(0xc000273380, 0xb6b980, 0xc000408180, 0xc000382a00, 0x0)
2020-06-19T19:25:31.678327+00:00 app[web.1]: /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccb
2020-06-19T19:25:31.678355+00:00 app[web.1]: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00043c050, 0xc000273380, 0xb6b980, 0xc000408180, 0xc000382a00)
2020-06-19T19:25:31.678360+00:00 app[web.1]: /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
2020-06-19T19:25:31.678364+00:00 app[web.1]: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-19T19:25:31.678379+00:00 app[web.1]: /go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1

**Comment by atye** [comment]
This seems to be caused by an unnecessary rowspan class on an element in the last row of the 28th table. 

This is the last tr element in the 28th table. The first td element has class rowspan="2" even though the actual row only spans a single row. 

```
<tr>
<td rowspan="2"><a href="/wiki/Jeju_language" title="Jeju language">Jeju</a>
</td>
<td><span class="datasortkey" data-sort-value="South Korea"><span class="flagicon"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" decoding="async" width="23" height="15" class="thumbborder" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" data-file-width="900" data-file-height="600">&nbsp;</span><a href="/wiki/South_Korea" title="South Korea">South Korea</a></span></td>
<td>official, in Jeju Island
</td>
</tr>
```

The table struct is not initialized with the additional row specified by the rowspan so we get a nil pointer exception when the table is populated. Fix will be to initialize the table rows as the table is parsed. In this case, the resulting json will have an extra row that doesn't match what is actually on the page. I think this is ok for now. The code assumes that the table is created properly.
